update=2013.09.02 16:25:27
version=1
last_client=cvpcb
[general]
version=1
[eeschema]
version=1
LibDir=D:/klondike-master/kicad/Footprints
NetFmtName=PcbnewAdvanced
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=special
LibName12=xilinx
LibName13=microcontrollers
LibName14=dsp
LibName15=microchip
LibName16=analog_switches
LibName17=motorola
LibName18=texas
LibName19=intel
LibName20=audio
LibName21=interface
LibName22=digital-audio
LibName23=philips
LibName24=display
LibName25=cypress
LibName26=siliconi
LibName27=opto
LibName28=atmel
LibName29=contrib
LibName30=valves
LibName31=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/tsop
LibName32=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/1wire
LibName33=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/74ah
LibName34=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/bourns
LibName35=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/burr-brown-2
LibName36=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/burr-brown-3
LibName37=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/burr-brown
LibName38=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/con-molex-2
LibName39=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/con-molex
LibName40=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/connect
LibName41=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/con-pci_express(pci-e)
LibName42=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/con-usb-3
LibName43=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/con-usb
LibName44=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/crystal
LibName45=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/diode-1
LibName46=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/diode
LibName47=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/filter-coilcraft
LibName48=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/i2c
LibName49=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/inductor-coilcraft
LibName50=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/led
LibName51=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/microchip
LibName52=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/nxp
LibName53=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/ref-packages
LibName54=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/smd-special
LibName55=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/special-diodes
LibName56=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/texas
LibName57=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/Footprints/transistor
LibName58=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/k16/k16
LibName59=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/kicad/k16/k16-cache
LibName60=C:/Program Files/KiCad/share/modules/converted/v-reg-lowdrop
LibName61=C:/Program Files/KiCad/share/modules/converted/linear2
LibName62=C:/Program Files/KiCad/share/modules/converted/linear3
LibName63=C:/Program Files/KiCad/share/modules/converted/linear4
LibName64=C:/Program Files/KiCad/share/modules/converted/linear-technology-3
LibName65=C:/Program Files/KiCad/share/modules/converted/v-reg-2
LibName66=C:/Program Files/KiCad/share/modules/converted/v-reg
LibName67=C:/Program Files/KiCad/share/modules/converted/v-reg-fairchild
[pcbnew]
version=1
LastNetListRead=bitfury.net
UseCmpFile=1
PadDrill=4.000000000000
PadDrillOvalY=4.000000000000
PadSizeH=7.000000000000
PadSizeV=7.000000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.350000000000
[pcbnew/libraries]
LibName1=sockets
LibName2=connect
LibName3=discret
LibName4=pin_array
LibName5=divers
LibName6=smd_capacitors
LibName7=smd_resistors
LibName8=smd_dil
LibName9=smd_transistors
LibName10=libcms
LibName11=display
LibName12=led
LibName13=dip_sockets
LibName14=pga_sockets
LibName15=valves
LibName16=capacitors
LibName17=connectors_molex_serial_53047-A123
LibName18=inductors
LibName19=muonde
LibName20=powerint
LibName21=k16
LibName22=standard
LibName23=tinkerforge
LibName24=Logo
LibName25=encoder
LibName26=1wire
LibName27=ref-packages
LibName28=con-pci_express(pci-e)
LibName29=diode
LibName30=diode-1
LibName31=C:/Documents and Settings/mlafleur/My Documents/Bitfury/klondike-master/Bitfury-fp
LibName32=inductor-coilcraft
LibName33=smd-special
LibName34=tsop
LibName35=bourns
LibName36=burr-brown-2
LibName37=burr-brown-3
LibName38=burr-brown
LibName39=con-molex-2
LibName40=con-molex
LibName41=con-usb-3
LibName42=con-usb
LibName43=crystal
LibName44=filter-coilcraft
LibName45=i2c
LibName46=microchip
LibName47=nxp
LibName48=special-diodes
LibName49=texas
LibName50=transistor
LibDir=D:/klondike-master/kicad/Footprints;D:/klondike-master/kicad/k16;../nano
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
